### ISSUE TITLE
能留个QQ号嘛~

### ISSUE THREAD

**Issue by loolksama** [buiawpkgew1/FN-FAL-s-Amplifications-zh#15]
核心1.18.1
RC-30/2022.3.2 测试过Build21 14-8 不能用
[21:52:02 ERROR]: Error occurred while enabling FNAmplifications vBuild 21 zh-CN(buiawpkgew1) (git 43f72eb) (Is it up to date?)
java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!
        at org.bstats.MetricsBase.checkRelocation(MetricsBase.java:220) ~[FNAmplifications-Build 21 zh-CN(buiawpkgew1) (git 43f72eb).jar:?]
        at org.bstats.MetricsBase.<init>(MetricsBase.java:104) ~[FNAmplifications-Build 21 zh-CN(buiawpkgew1) (git 43f72eb).jar:?]
        at org.bstats.bukkit.Metrics.<init>(Metrics.java:74) ~[FNAmplifications-Build 21 zh-CN(buiawpkgew1) (git 43f72eb).jar:?]
        at ne.fnfal113.fnamplifications.FNAmplifications.onEnable(FNAmplifications.java:38) ~[FNAmplifications-Build 21 zh-CN(buiawpkgew1) (git 43f72eb).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.18.1.jar:git-Paper-81]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-81]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:52:02 INFO]: [FNAmplifications] Disabling FNAmplifications vBuild 21 zh-CN(buiawpkgew1) (git 43f72eb)
[21:52:02 INFO]: [FNAmplifications] Cancelled any running task that exist

**Comment by loolksama** [comment]
使用官方DEV 53 (git a51c0) 可以使用

**Comment by loolksama** [comment]
Paper git-Paper-81 (MC: 1.18.1)
Slimefun RC - 30 (git fd4b462f)
Metrics-Module #28
Java 17
FNAmplifications vDEV - 53 (git a51c0d7b)

**Comment by buiawpkgew1** [comment]
@loolksama qq:750215287
