### ISSUE TITLE
开服发生报错,然后插件被关闭,是不是经济插件问题?

### ISSUE THREAD

**Issue by xiaofengv233** [buiawpkgew1/FN-FAL-s-Amplifications-zh#182]
[14:42:32 INFO]: [FNAmplifications] Enabling FNAmplifications vBuild 17 (git 0a3acd4)
[14:42:32 INFO]: [FNAmplifications] ************************************************************
[14:42:32 INFO]: [FNAmplifications]               FN Amplifications - FN 科技
[14:42:32 INFO]: [FNAmplifications]            作者: FN_FAL113  汉化: lroj,haiman233,SlimefunGuguProject
[14:42:32 INFO]: [FNAmplifications]     感谢 Jeff(LiteXpansion) 与 Walshy(Slimefun) 提供的工具包
[14:42:32 INFO]: [FNAmplifications]                如有任何问题，请前往问题追踪器汇报
[14:42:32 INFO]: [FNAmplifications]                 作者 Discord: FN_FAL#7779
[14:42:32 INFO]: [FNAmplifications] ************************************************************
[14:42:32 INFO]: [FNAmplifications] 检测到Vault API！Loot Gem 将被注册。
[14:42:32 ERROR]: Error occurred while enabling FNAmplifications vBuild 17 (git 0a3acd4) (Is it up to date?)
java.lang.NoClassDefFoundError: net/guizhanss/guizhanlibplugin/updater/GuizhanBuildsUpdaterWrapper
        at FN-FAL-s-Amplifications-Build 17 (git 0a3acd4).jar/ne.fnfal113.fnamplifications.FNAmplifications.onEnable(FNAmplifications.java:57) ~[FN-FAL-s-Amplifications-Build 17 (git 0a3acd4).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.1.jar:1.21.1-2323-4671e1e]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.1.jar:1.21.1-2323-4671e1e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.1.jar:1.21.1-2323-4671e1e]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.1.jar:1.21.1-2323-4671e1e]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.1.jar:1.21.1-2323-4671e1e]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.1.jar:1.21.1-2323-4671e1e]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366) ~[purpur-1.21.1.jar:1.21.1-2323-4671e1e]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.1.jar:1.21.1-2323-4671e1e]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2323-4671e1e]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.guizhanss.guizhanlibplugin.updater.GuizhanBuildsUpdaterWrapper
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 13 more
[14:42:32 INFO]: [FNAmplifications] Disabling FNAmplifications vBuild 17 (git 0a3acd4)
[14:42:32 INFO]: [FNAmplifications] 已取消所有正在执行的任务

**Comment by buiawpkgew1** [comment]
- 服务器软件和版本（Spigot/Paper）：
 - Minecraft 版本：
 - Slimefun 版本：
 - FNAmplification 版本：

**Comment by xiaofengv233** [comment]
> * 服务器软件和版本（Spigot/Paper）：
> * Minecraft 版本：
> * Slimefun 版本：
> * FNAmplification 版本：
>   将服务器日志上传剪贴板并提供链接（以下任选一）：
>   https://paste.guizhanss.net/
>   https://pastebin.com/
>   https://mclo.gs/

感谢提醒,但是好像现在可以了,刚才去鬼斩那下了个新版本
