### ISSUE TITLE
装不上

### ISSUE THREAD

**Issue by loolksama** [buiawpkgew1/FN-FAL-s-Amplifications-zh#7]
Error occurred while enabling FNAmplifications vBuild 12 zh-CN(buiawpkgew1) (git 1ef3a44) (Is it up to date?)
java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!
at org.bstats.MetricsBase.checkRelocation(MetricsBase.java:220) ~[?:?]
at org.bstats.MetricsBase.<init>(MetricsBase.java:104) ~[?:?]
at org.bstats.bukkit.Metrics.<init>(Metrics.java:74) ~[?:?]
at ne.fnfal113.fnamplifications.FNAmplifications.onEnable(FNAmplifications.java:36) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[PaperSpigot-1.16.5.jar:git-Paper-794]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[PaperSpigot-1.16.5.jar:git-Paper-794]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[PaperSpigot-1.16.5.jar:git-Paper-794]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[PaperSpigot-1.16.5.jar:git-Paper-794]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[PaperSpigot-1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[PaperSpigot-1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[PaperSpigot-1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[PaperSpigot-1.16.5.jar:git-Paper-794]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[PaperSpigot-1.16.5.jar:git-Paper-794]
at java.lang.Thread.run(Thread.java:831) [?:?]
[23:27:11 INFO]: [FNAmplifications] Disabling FNAmplifications vBuild 12 zh-CN(buiawpkgew1) (git 1ef3a44)

**Comment by loolksama** [comment]
> @loolksama 完成了

感谢~
