### ISSUE TITLE
但是但是= =

### ISSUE THREAD

**Issue by loolksama** [buiawpkgew1/FN-FAL-s-Amplifications-zh#8]
[FNAmplifications] Enabling FNAmplifications vBuild 13 zh-CN(buiawpkgew1) (git 27fdad0)
[11:49:16 ERROR]: Error occurred while enabling FNAmplifications vBuild 13 zh-CN(buiawpkgew1) (git 27fdad0) (Is it up to date?)
java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!
at org.bstats.MetricsBase.checkRelocation(MetricsBase.java:220) ~[FNAmplifications-Build 13 zh-CN(buiawpkgew1) (git 27fdad0).jar:?]
at org.bstats.MetricsBase.<init>(MetricsBase.java:104) ~[FNAmplifications-Build 13 zh-CN(buiawpkgew1) (git 27fdad0).jar:?]
at org.bstats.bukkit.Metrics.<init>(Metrics.java:74) ~[FNAmplifications-Build 13 zh-CN(buiawpkgew1) (git 27fdad0).jar:?]
at ne.fnfal113.fnamplifications.FNAmplifications.onEnable(FNAmplifications.java:36) ~[FNAmplifications-Build 13 zh-CN(buiawpkgew1) (git 27fdad0).jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[PaperSpigot-1.17.1.jar:git-Paper-409]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[PaperSpigot-1.17.1.jar:git-Paper-409]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[PaperSpigot-1.17.1.jar:git-Paper-409]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[PaperSpigot-1.17.1.jar:git-Paper-409]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[PaperSpigot-1.17.1.jar:git-Paper-409]
at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[PaperSpigot-1.17.1.jar:git-Paper-409]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[PaperSpigot-1.17.1.jar:git-Paper-409]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[PaperSpigot-1.17.1.jar:git-Paper-409]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[PaperSpigot-1.17.1.jar:git-Paper-409]
at java.lang.Thread.run(Thread.java:831) ~[?:?]
[11:49:16 INFO]: [FNAmplifications] Disabling FNAmplifications vBuild 13 zh-CN(buiawpkgew1) (git 27fdad0)

**Comment by loolksama** [comment]
服务器版本是1.17.1
sf版本金丝雀 ad3dd44

**Comment by buiawpkgew1** [comment]
> 服务器版本是1.17.1 sf版本金丝雀 ad3dd44

你不用汉化试试

**Comment by buiawpkgew1** [comment]
我不会java

**Comment by loolksama** [comment]
> > 服务器版本是1.17.1 sf版本金丝雀 ad3dd44
> 
> 你不用汉化试试

要求的工业插件版本和SMG版本都达到 用第一

> 我不会java

辛苦了 但是好像9版本还是1版本可以用

**Comment by buiawpkgew1** [comment]
@loolksama 又更新了 你试一下
